version: '3.3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    command: --storageEngine wiredTiger
    volumes:
       - mongovolume:/data/mongo
  messaging:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
volumes:
  mongovolume:
